volumes:
  dbdata:


services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=mlflowdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  tracker:
    build: .
    container_name: tracker
    image: mlflow-tracker:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mlflowdb
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MINIO_URL}
      - MLFLOW_S3_IGNORE_TLS=true
      - ARTIFACT_ROOT=s3://${MINIO_BUCKET_NAME}/
    depends_on:
      - db
    restart: unless-stopped
