version: "3.7"

services:

  db:
    image: postgres:latest
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mlflowdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata

  tracker:
    build: .
    container_name: tracker
    image: mlflow-tracker:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/backend:/data/backend
    environment:
      - DB_HOST=db
      - DB_NAME=mlflowdb
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    depends_on:
      - db
