version: '3'

services:
  # db:
  #   container_name: db
  #   image: postgres:latest
  tracker:
    container_name: tracker
    image: mlflow-tracker:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/backend:/data/backend
