version: "3.7"

volumes:
  dbdata:


services:

  # TODO: set up backups https://stackoverflow.com/a/29913462
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=mlflowdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  tracker:
    build: .
    container_name: tracker
    image: mlflow-tracker:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mlflowdb
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    depends_on:
      - db
